title: Gallix
author: Mariano Agustín Gallicchio
description: "Gallix - Software Development & Creative Tech"
theme: minima
show_downloads: false
port_plugins:
  - jekyll-redirect-from

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    block:
      line_numbers: false

defaults:
  - scope:
      path: ""
    values:
      layout: default
